name:CI

on:
push:
branches:[main]
pull_request:
branches:[main]

jobs:
build:
runs-on:ubuntu-latest

steps:
-uses:actions/checkout@v2
-name:SetupPython3.8
uses:actions/setup-python@v2
with:
python-version:3.8
-name:InstallPoetry
run:pipinstallpoetry
-name:Installdependencies
run:poetryinstall
-name:Runtests
run:poetryruncoveragerun--branch-mpytest
-name:Coveragereport
run:poetryruncoveragexml
-name:CoveragereporttoCodecov
uses:codecov/codecov-action@v2

